services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm run tsc && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4500:4500"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run dev"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elk-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: elk-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    volumes:
      - ./elk/kabana-config/setup.sh:/usr/local/bin/setup_kibana.sh
      - ./elk/kabana-config/dashboards:/usr/local/bin/dashboards
    command: bash /usr/local/bin/setup_kibana.sh
    depends_on:
      - elasticsearch


  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: elk-logstash
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch

  nginx:
    ports:
      - "62000:80"
    build:
      context: ./elk/nginx
    volumes:
      - ./elk/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    container_name: elk-nginx
    depends_on:
      - elasticsearch
      - kibana
      - logstash



volumes:
  esdata:
