services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./certs:/tmp/ssl:ro
    ports:
      - "3000:3000"
    networks:
      - webnet
    working_dir: /app
    command: sh -c "npm install && npm run tsc && npm run dev"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - METAMASK_KEY=${METAMASK_KEY}
    ports:
      - "4500:4500"
    volumes:
      - ./backend:/app
      - shared-data:/vault/token/
      - ./certs:/tmp/ssl:ro
    working_dir: /app
    networks:
      - webnet
    command: sh -c "npm install && npm run build && npm run dev"
  hashicorp_vault:
    build:
      context: ./hashicorp_vault
      dockerfile: Dockerfile
    ports:
      - "8300:8300"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: https://localhost:8300
    volumes:
      - shared-data:/vault/token/
      - ./certs:/tmp/ssl:ro
    networks:
      - webnet
  waf:
    build:
      context: ./waf
      dockerfile: Dockerfile
    ports:
      - "3100:6000"
    networks:
      - webnet
    volumes:
      - ./certs:/tmp/ssl:ro
    depends_on:
      - frontend
      - backend
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elk-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - webnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.1
    container_name: elk-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
    volumes:
      - ./elk/kibana-config/setup.sh:/usr/local/bin/setup_kibana.sh
      - ./elk/kibana-config/dashboards:/usr/local/bin/dashboards
    command: bash /usr/local/bin/setup_kibana.sh
    depends_on:
      - elasticsearch
    networks:
      - webnet

  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.1
    container_name: elk-logstash
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - webnet
  nginx:
    ports:
      - "62000:80"
      - "62001:443"
    build:
      context: ./elk/nginx
    volumes:
      - ./elk/nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./certs:/tmp/ssl:ro
    container_name: elk-nginx
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    networks:
      - webnet


volumes:
  esdata:
  shared-data:

networks:
  webnet:
    driver: bridge