FROM docker.elastic.co/kibana/kibana:8.12.1

COPY ./kabana-config/setup.sh /usr/local/bin/setup_kibana.sh
COPY ./kabana-config/dashboards /usr/local/bin/dashboards

ENTRYPOINT ["/bin/bash", "-c", "/usr/local/bin/setup_kibana.sh && /usr/local/bin/kibana-docker"]
