server.host: "0.0.0.0"
server.ssl.enabled: true
server.ssl.certificate: /usr/share/kibana/config/certs/fullchain.crt
server.ssl.key: /usr/share/kibana/config/certs/transcendence.key

server.basePath: "/kibana"
server.rewriteBasePath: true

elasticsearch.hosts: [ "https://elasticsearch:9200" ]
elasticsearch.username: "${ELASTIC_USERNAME}"
elasticsearch.password: "${ELASTIC_PASSWORD}"
elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/config/certs/ca.crt" ]
elasticsearch.ssl.verificationMode: certificate
